### ISSUE TITLE
1.12.2 port [Feature Request]

### ISSUE THREAD

**Issue by Foreck1** [thraaawn/RiddleChests#1]
Sorry if this something you don't want to read, but I didn't see a disclaimer anywhere saying that this isn't going to happen.
I don't know if mixins have something to do with not being able to downgrade to 1.12, but this mod's concept is really fun and interesting and I think that it would fit perfectly in 1.12 modded playthroughs. Thanks for your time

**Comment by davenonymous** [comment]
It's ok to ask for this, I fully understand.

I probably have to disappoint you though 😞 currently i have no plans of porting this back to 1.12.
On the other hand, I actually started development of this mod in 1.12, so there is some code that runs on 1.12 it's just not finished and would require one or two full days of tinkering.

Well, maybe. Not before I ported Compact Machines to 1.14 though.

**Comment by Foreck1** [comment]
I appreciate the glimpse of hope. then I will leave this issue open for the future just in case. Thanks for the response and don't stop enjoying what you do!
