### ISSUE TITLE
Riddle chests don't spawn with other mods that overwrite vanilla chests

### ISSUE THREAD

**Issue by DWX12** [thraaawn/RiddleChests#10]
There are a few mods out there that overwrite/replace and possibly remove vanilla loot chests.
One such mod is Lootr:
https://www.curseforge.com/minecraft/mc-mods/lootr

In my limited testing with both mods, I did not encounter any Riddle Chests in the world.

I'm not sure how to remedy the issue except for maybe generating Riddle Chests in close proximity to loot chests that would naturally generate, if possible. Maybe chat with the dev Noobanidus to see if some sort of support can be added such as player instanced Riddle Chests.

Thanks for taking the time to create such a cool mod.

**Comment by davenonymous** [comment]
Hmm, there should be support for Lootr chests included. May I ask how you tested?
Try setting the chance to replace chests to 100% and teleport to the nearest village. It should have riddle chests even though Lootr is installed.

**Comment by DWX12** [comment]
It was a brief test whilst trying to get a mod pack I'm making working. I'll do more testing when I take some time to do so.

**Comment by DWX12** [comment]
Finally got around to doing a bit more testing. You are correct that they do spawn with mods such as Lootr; however, the spawn rate is much lower compared to no other mods that change vanilla chest spawn behavior.

I will go ahead and close this issue as there is none except for the lowered spawn rate.

Thanks again.
