### ISSUE TITLE
Get "Oops. Unknown alphabet..." message on servers

### ISSUE THREAD

**Issue by darkphan** [thraaawn/RiddleChests#4]
Riddle Chest version: RiddleChests-1.0.1.16
Forge: 28.2.0
Minecraft: 1.14.4

When trying to open Riddle Chests on a server you get "Oops. Unknown alphabet for this riddle."

**Comment by davenonymous** [comment]
Oops.

**Comment by davenonymous** [comment]
Fingers crossed that the latest build fixes the issue. I haven't actually tested it, but it's essentially the same issue as the 1.15 version had. I'm just going to release it on curse.

Will be [here](https://www.curseforge.com/minecraft/mc-mods/riddle-chests/files/2876288) once approved.
If you don't want to wait you can also grab it from the maven [here](http://maven.davenonymous.com/repository/maven-public/com/davenonymous/riddlechests/RiddleChests/1.0.2.3/RiddleChests-1.0.2.3.jar).

**Comment by darkphan** [comment]
I can confirm that this fixed the issue. Thanks!
