### ISSUE TITLE
Riddle not showing up

### ISSUE THREAD

**Issue by thaKnza** [thraaawn/RiddleChests#5]
I have a player on my forge server who's riddle is not displaying at all. She plays on Mac OS. The riddles show up for me, I play on Windows.

Not sure if the platform is related but just a guess.

**Comment by davenonymous** [comment]
You have to define more precisely what "not showing up" means. No GUI at all? Missing text? Missing buttons? Neither? Which version of Riddle Chests? Is it showing any error messages on screen or in the log?
Without any more information I will not be able to reproduce this.

**Comment by thaKnza** [comment]
The latest version on CurseForge, RiddleChests-1.0.2.3.

The GUI shows up but not the text of the riddles. Users see the letter selection but not the riddle itself. Here's a picture the person took of their screen. No errors on screen during gameplay, no crashes. I will try to get this person to check their logs.

![84129786_118157066302368_6660950254063452160_n](https://user-images.githubusercontent.com/53676750/74255412-d5f09600-4cbf-11ea-9128-6f0cf522269d.jpg)

This happens consistently for this user every single time they find a riddle chest. Other people are able to check the chest and tell her what the riddle is, and then if she puts in the correct answer it unlocks for her despite not showing any riddle on her end.

**Comment by davenonymous** [comment]
Huh. That's really odd. Do you happen to know the resolution she's playing in? That screen should also be fullscreen. Odd indeed.

**Comment by thaKnza** [comment]
I couldn't get a direct answer on what res she was running, but now both of my Mac OS users have tested the mod and both of them have the same problem. Riddle doesn't show up, and the UI isn't full screen.

**Comment by thaKnza** [comment]
I am hoping that if you can't figure this out, perhaps you could release a version that prints the riddle into the user's chat or something?

**Comment by davenonymous** [comment]
Unless I find an easy fix for the problem I'll add a client-side config option that allows for that. Good idea!

**Comment by AlexHuntsman** [comment]
Any update, seems it is still a very common issue.

**Comment by connor29914** [comment]
Another Mac user here, unable to read the riddle chests. Only current solution is to communicate the waypoint to another member of my server and have them open it.
